### ISSUE TITLE
默认的日志级别或许不应设置为DEBUG？

### ISSUE THREAD

**Issue by Lancercmd** [nonebot/plugin-apscheduler#1]
控制台被高强度刷屏了（
https://github.com/nonebot/plugin-apscheduler/blob/86159c06cce146494476a19c0ce4519b5efd1921/nonebot_plugin_apscheduler/__init__.py#L28

**Comment by yanyongyu** [comment]
这里设置debug是为了将debug日志输出到nonebot的logger，在nonebot的logger中有一层filter过滤后才会输出到控制台

由于nonebot配置里设置了debug，所以日志过滤等级为debug

**Comment by yanyongyu** [comment]
已修改
