### ISSUE TITLE
使用插件报错找不到 getprop

### ISSUE THREAD

**Issue by 1409109991** [nonebot/plugin-apscheduler#13]
![image](https://user-images.githubusercontent.com/79674967/186310561-c69b9da1-6a7f-4dc5-b2f0-939bbbdf7afd.png)
我在手机上装这个插件，报这个错我不知道怎么解决

**Comment by yanyongyu** [comment]
termux 缺少了一点东西，查了下你可以试试安装 `apt-file` 里面有 `getprop`

```bash
pkg install apt-file
apt-file update
apt-file list termux-tools
```

**Comment by 1409109991** [comment]
我去试试

**Comment by 1409109991** [comment]
我这个系统要安装什么包啊
![image](https://user-images.githubusercontent.com/79674967/211186057-c0aa609c-ff9d-4a43-92d2-411ebd94d062.png)
这是我旧手机刷kali玩的，准备装机器人，然后缺这个东西 **getgrop**
