### ISSUE TITLE
Failed to import

### ISSUE THREAD

**Issue by Danwk2333** [nonebot/plugin-apscheduler#15]
![U3SEJG}D4N_Z9_K@Y3C{D~6](https://user-images.githubusercontent.com/106854600/195522253-da019d9c-2baf-4d22-b467-b0df3feaf4fd.png)
![}`VO69%3{7B$%0PWS`IA1D](https://user-images.githubusercontent.com/106854600/195522268-0564bfe9-7c97-4a49-a9cd-8899a766c623.png)

**Comment by yanyongyu** [comment]
升级插件`pip install --upgrade nonebot-plugin-apscheduler`
