### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by QwindF** [nonebot/plugin-apscheduler#20]
![Q}( GEDM68LKQC7 ZQY0P{9](https://user-images.githubusercontent.com/87116340/216759560-ec235a88-d5ae-4fbc-b05d-36501a4c2977.png)

windows10下,pycharm运行
插件最新版本

**Comment by yanyongyu** [comment]
这报错与apscheduler插件无关，是bilireq的问题，请求取消

**Comment by QwindF** [comment]
好的，谢谢
