### ISSUE TITLE
加载错误

### ISSUE THREAD

**Issue by xueqi5201314** [nonebot/plugin-apscheduler#23]
首先是nonebot_plugin_myb_exchange插件依赖于您的插件
![image](https://user-images.githubusercontent.com/108047693/226634740-86df2472-b13f-4c36-b445-d8603aedc363.png)
但是我安装完成后，你的插件就报错
![image](https://user-images.githubusercontent.com/108047693/226635110-138d5414-f6d0-4fd6-b8f6-9b5381105542.png)
不知道怎么回事，加上我不会英语（日语生），所以来问问你
我使用的是基于云崽py插件的nonebot

**Comment by yanyongyu** [comment]
我不知道yunzai怎么写的加载，或许你可以看看pyproject.toml之类的文件
