### ISSUE TITLE
导入出错，TypeError: entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by Dramwig** [nonebot/plugin-apscheduler#33]
![image](https://github.com/nonebot/plugin-apscheduler/assets/54499515/58ba4531-5ce1-476b-967e-08ddc2443e16)
Version：
nonebot-plugin-apscheduler 0.3.0
APScheduler                3.10.2
nonebot2                   2.0.1

**Comment by Dramwig** [comment]
解决方法：将APScheduler 回退至3.9.1

**Comment by yanyongyu** [comment]
请检查你的python与importlib_metadata的版本
