### ISSUE TITLE
Bug: Apscheduler 加载报错

### ISSUE THREAD

**Issue by WTTSFW** [nonebot/plugin-apscheduler#35]
![image](https://github.com/nonebot/plugin-apscheduler/assets/85236395/0c86accc-729c-48c4-bb2f-733610a444d6)
![61I2_N}FXBY%8(WWR1LQP6S](https://github.com/nonebot/plugin-apscheduler/assets/85236395/f6f163d7-baef-49d5-955f-a29d73295331)

**Comment by yanyongyu** [comment]
你的python版本和importlib_metadata的版本是什么

**Comment by WTTSFW** [comment]
![LRDSXD`UU)Y7(4OEQ9CT{VD](https://github.com/nonebot/plugin-apscheduler/assets/85236395/f750b25f-638d-4c35-ad4d-801ff6a67833)

**Comment by WTTSFW** [comment]
importlib_metadata版本怎么看

**Comment by yanyongyu** [comment]
`pip show importlib-metadata`

**Comment by yanyongyu** [comment]
看了下应该是apscheduler在python3.9下的问题

**Comment by yanyongyu** [comment]
https://github.com/agronholm/apscheduler/pull/773

**Comment by yanyongyu** [comment]
仅在python3.9有问题，会在下次apscheduler发版后修复
