### ISSUE TITLE
启动任务问题

### ISSUE THREAD

**Issue by kentelove** [nonebot/plugin-apscheduler#9]
apscheduler_autostart = false 后,
怎么在程序运行时,启动?

**Comment by kentelove** [comment]
设置 apscheduler_autostart = false 后,

代码:
def play_game():
      print('你好呀!')

scheduler = require("nonebot_plugin_apscheduler").scheduler
job = scheduler.add_job(play_game, 'interval', seconds=3)
scheduler.start()

不报错,但任务不起动.运行.还请大佬指导..

**Comment by yanyongyu** [comment]
在你需要启动scheduler的时候，调用`scheduler.start()`。默认autostart会在bot启动时启动schduler

**Comment by kentelove** [comment]
> 在你需要启动scheduler的时候，调用`scheduler.start()`。默认autostart会在bot时启动schduler

照大佬说的,在需要的事件里调用, scheduler.start() 确实成功了. 但我没有搞懂,这个区别在哪里?

我上面的代码,为什么就不成功呢?   好像,就是调用 scheduler.start()  的时间不同.

**Comment by yanyongyu** [comment]
scheduler应该在server进程中进行启动，而不是在主进程里启动

**Comment by kentelove** [comment]
学习了..谢谢您!
